import nucleotide

Import('settings')


# Accumulate source
source = []
source +=   ['main.cpp'] 


# Make native environment
envProgram = nucleotide.Environment( settings ).native()

# Create program
exe_name =  'main-' + settings.get_custom('architecture')

program = envProgram.Program( target =  exe_name + envProgram['PROGSUFFIX'], source = source  )

# ... and return!
Return( 'program' )

