call %prg_scons% architecture=x86_64
call %prg_scons% architecture=i586
call %prg_scons% architecture=x86
call %prg_scons% architecture=x86_amd64
call %prg_scons% architecture=i486
call %prg_scons% architecture=emt64
call %prg_scons% architecture=i386
call %prg_scons% architecture=ia64
call %prg_scons% architecture=itanium
rem call %prg_scons% architecture=amd64
call %prg_scons% architecture=i686
