import nucleotide

Import('settings')


# Accumulate Atoms
## Avoid complain of MSVC
settings.accumulate( 'exception' )

settings.accumulate( 'compiler:rebuild:lazy', { 'enable' : 'true' } )
settings.accumulate( 'PDB', { 'format': 'classic', 'synchronous' : 'false', 'file-name': './main.pdb' } )


# Accumulate source
source = []
source +=   ['main.cpp'] 

# Make native environment
envProgram = nucleotide.Environment( settings ).native()

# Create program
program = envProgram.Program( target =  'main' + envProgram['PROGSUFFIX'], source = source  )

# ... and return!
Return( 'program' )
