import nucleotide

Import('settings')

# Accumulate Atoms

## Enable exceptions
settings.accumulate( 'exception' )

## Set Program Database File
settings.accumulate( 'PDB', { 'configuration': 'release', 'synchronous' : 'false', 'file-name': './main.pdb' } ) 

# Accumulate source
source = []
source +=   ['main.cpp'] 

# Make native environment
envProgram = nucleotide.Environment( settings ).native()

# Create program
program = envProgram.Program( target =  'main' + envProgram['PROGSUFFIX'], source = source  )

# ... and return!
Return( 'program' )
