
import nucleotide

#make setting
settings = nucleotide.Settings( )

#Accumulate 
settings.accumulate( 'exception' )
settings.accumulate( 'compiler:version', { 'gcc' : ['4.8'], 'msvc': ['12.0'] } )

# Call
product = SConscript('./SConscript', exports=[ 'settings' ] )

#Make it defualt
Default( product )


