import nucleotide

Import('settings')


# Accumulate Atoms

## Enable exceptions
settings.accumulate( 'exception' )

## Set Run Time Library
settings.accumulate( 'compiler:memory:alignment', { 'size' : '8' } )

# Accumulate source
source = []
source +=   ['main.cpp']

# Make native environment
envProgram = nucleotide.Environment( settings ).native()

# Create program
program = envProgram.Program( target =  'main' + envProgram['PROGSUFFIX'], source = source  )

# ... and return!
Return( 'program' )
