import nucleotide

Import('settings')


# Accumulate Atoms
## accumulate my-extension
## WARNING:  Ensure that  'my-extension' exists when you call this SConscript
settings.accumulate( 'my-extension' )

settings.accumulate( 'exception' )

# Accumulate source
source = []
source +=   ['main.cpp'] 


# Make native environment
envProgram = nucleotide.Environment( settings ).native()

# Create program
program = envProgram.Program( target =  'main' + envProgram['PROGSUFFIX'], source = source  )

# ... and return!
Return( 'program' )
 