import nucleotide

Import('settings')


# Accumulate Atoms
## Avoid complain of MSVC
settings.accumulate( 'exception' )
## Add boost
settings.accumulate( 'boost:blank', { 'architecture' : 'x86'  } )
settings.accumulate( 'architecture' , { 'name' : 'x86'  } )

# Accumulate source
source = []
source +=   ['main.cpp'] 

# Make native environment
envProgram = nucleotide.Environment( settings ).native()

# Create program
program = envProgram.Program( target =  'main' + envProgram['PROGSUFFIX'], source = source  )

# ... and return!
Return( 'program' )
